apiVersion: apps/v1
kind: Deployment
metadata: 
 namespace: rapa
 name: default
spec:
 replicas: 3
 selector:
   matchLabels:
     app: default # replicas 
 template: # pod 정의 
   metadata: 
     name: default # pod 이름 
     labels:
       app: default # 3개 생성 
   spec:
     containers: 
     - name: default
       image: nginx
       ports: 
       - containerPort: 80
       volumeMounts:
       - name: defaultvol
         mountPath: /usr/share/nginx/html
     volumes:
     - name: defaultvol
       configMap:
         name: defaultcm
---
apiVersion: v1
kind: Service
metadata: 
  namespace: rapa 
  name: default
spec:
 ports:
 - name: default-port
   port: 80 # service의 포트
   targetPort: 80 # pod의 포트
   nodePort: 30001
 selector:
   app: default # pod의 label
 type: NodePort