apiVersion: apps/v1
kind: Deployment
metadata: 
#  namespace: rapa
 name: news
spec:
 replicas: 3
 selector:
   matchLabels:
     app: news # replicas 
 template: # pod 정의 
   metadata: 
     name: news # pod 이름 
     labels:
       app: news # 3개 생성 
   spec:
     containers: 
     - name: news
       image: nginx
       ports: 
       - containerPort: 80
       volumeMounts:
       - name: newsvol
         mountPath: /usr/share/nginx/html
     volumes:
     - name: newsvol
       configMap:
         name: newscm
---
apiVersion: v1
kind: Service
metadata: 
  # namespace: rapa 
  name: news
spec:
 ports:
 - name: news-port
   port: 80 # service의 포트
   targetPort: 80 # pod의 포트
   nodePort: 30003
 selector:
   app: news # pod의 label
 type: NodePort